In [1]:
import numpy as np

In [12]:
arr1 = np.array([1,2,3]) #리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환
print(type(arr1))
print(arr1.shape) #1차원

arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(type(arr2))
print(arr2.shape) #2차원, 2행 3열

arr3 = np.array([[1,2,3]])
print(type(arr3))
print(arr3.shape) #2차원, 1행

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [17]:
list = [1,2,3]
print(type(list))
arr4 = np.array(list)
print(arr4, arr4.dtype) #dtype은 ndarray내 데이터타입확인

<class 'list'>
[1 2 3] int32


In [20]:
list2 = [1,2,'apple']
arr5 = np.array(list2)
print(arr5, arr5.dtype) #int형 1과 2가 모두 문자형으로 변환
#np.array함수 실행 시 서로 다른 데이터 타입이 섞여 있을 경우 타입이 더 큰 데이터 타입으로 변환. 

['1' '2' 'apple'] <U11


In [28]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') #ndarray속 변수들의 형태를 변경
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [32]:
sequence_array = np.arange(10) #array를 range()로 표현하는 것
print(sequence_array) 
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [42]:
zero_array = np.zeros((3,2), dtype='int32') #모든 값을 0으로 채운 행렬 생성 
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array = np.ones((3,2)) #모든 값을 1로 채운 행렬 생성
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [62]:
array = np.arange(10) 
array2 = array.reshape(2,5)#darray를 특정 차원 및 크기로 변환 
print(array2)

array3 = array.reshape(5,2)
print(array3)

array4 = array.reshape(-1,2) #인자를 -1로 쓰면 원래ndarray와 호환되는 shape로 변환해준다.
print(array4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


인덱싱[Indexing]

In [68]:
arr = np.arange(1,10)
value = arr[2]
print(value)
value2 = arr[-1] #뒤에서부터 인덱싱
print(value2)

3
9


In [77]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
value1 = array2d[0,0] #다차원에서 인덱싱
value2 = array2d[1,0]
print(value1, value2)

#axis 0는 행방향, axis 1은 열방향을 의미한다.

1 4


In [80]:
arr = np.arange(1,10)
values = arr[0:5]#슬라이싱
values

array([1, 2, 3, 4, 5])

In [85]:
arr = np.arange(1, 10)
arr2 = arr.reshape(3,3)
values = arr2[0:2, 0:2] #다차원 슬라이싱은 axis 0부터 한 뒤 axis 1까지 슬라이싱 하는 것이다.
print(values)

print(arr2[0]) #첫번째 로우를 전부 반환한다.
print(arr2[1])

[[1 2]
 [4 5]]
[1 2 3]
[4 5 6]


In [88]:
#불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식이다.
array1d = np.arange(1,10)
arrBool = array1d[array1d>5] #5보다 큰 값만 저장
print(arrBool)

[6 7 8 9]


행렬의 정렬(sort()와 argsort())

In [92]:
org_array = np.array([3,1,9,5])
org_array2 = np.array([5,3,6,1])
SortedArray = np.sort(org_array) #org_array를 sorting하고 반환
org_array2.sort() #org_array2자체를 sorting한다

array([1, 3, 5, 6])

In [99]:
array2d = np.array([[8,12],
                   [7,1]])

array2d.sort(axis=0) #row방향으로 sorting
array2d.sort(axis=1) #col방향으로 sorting

print(array2d_index)

array2d

[[0 1]
 [1 0]]


array([[ 1,  7],
       [ 8, 12]])

In [101]:
arr = np.array([3,2,1])
array2d_index = np.argsort(arr)#정렬된 순서의 index를 반환한다.
print(array2d_index)

[2 1 0]


선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [103]:
#행렬내적은 행렬의 곱
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B) #행렬의 곱을 구하는 함수 np.dot
print(dot_product)

[[ 58  64]
 [139 154]]


In [106]:
#전치행렬은 행렬의 행
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
